# -*- coding: utf-8 -*-
"""Leasing Company Google Review

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1If54rrc5XvvhAi84ObdzCbiSrm-v_YT2

# Clean Leasing Company Google Reviews

Use this starter notebook to load raw data files.
"""

import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 100)

"""## Load data

### Businesses and reviews

Read the CSV files. These are [Outscraper](https://outscraper.com/)'s scraped output. They contain Google reviews for leasing companies, apartment complexes, and student housing for three different campustowns.

- Brigham Young University (Provo, UT)
- Penn State University (University Park, PA)
- University of Illinois at Urbana Champaign (Champaign, IL)
"""

df_byu_b = pd.read_csv('https://github.com/bdi475/datasets/raw/main/campustowns-leasing-company-reviews/byu-businesses.csv')
df_byu_r = pd.read_csv('https://github.com/bdi475/datasets/raw/main/campustowns-leasing-company-reviews/byu-reviews.csv')
df_psu_b = pd.read_csv('https://github.com/bdi475/datasets/raw/main/campustowns-leasing-company-reviews/psu-businesses.csv')
df_psu_r = pd.read_csv('https://github.com/bdi475/datasets/raw/main/campustowns-leasing-company-reviews/psu-reviews.csv')
df_uiuc_b = pd.read_csv('https://github.com/bdi475/datasets/raw/main/campustowns-leasing-company-reviews/uiuc-businesses.csv')
df_uiuc_r = pd.read_csv('https://github.com/bdi475/datasets/raw/main/campustowns-leasing-company-reviews/uiuc-reviews.csv')

display(df_byu_b.head(2))
display(df_byu_r.head(2))
display(df_psu_b.head(2))
display(df_psu_r.head(2))
display(df_uiuc_b.head(2))
display(df_uiuc_r.head(2))

"""### NLP

Read the token list (through spaCy) and sentiment analysis results (using DistilBERT) so that you don't have to run the entire text analysis (which can take over an hour).
"""

df_tokens = pd.read_csv('https://github.com/bdi475/datasets/raw/main/campustowns-leasing-company-reviews/results/tokens.csv.gz')
df_sentiments = pd.read_csv('https://github.com/bdi475/datasets/raw/main/campustowns-leasing-company-reviews/results/sentiments.csv')

display(df_tokens.head(3))
display(df_sentiments.head(3))

"""#Question 1 - How does the management companies in UIUC compare to the two other campuses?"""

df_b = pd.concat([df_byu_b,df_psu_b,df_uiuc_b])
df_r = pd.concat([df_byu_r,df_psu_r,df_uiuc_r])

import pandas as pd
import plotly.graph_objects as go
import plotly.express as px

df_campus_wide = df_b.groupby(['state'], as_index=False).agg({
    'reviews_per_score_1': 'sum',
    'reviews_per_score_2': 'sum',
    'reviews_per_score_3': 'sum',
    'reviews_per_score_4': 'sum',
    'reviews_per_score_5': 'sum',
})

df_campus_wide['state'] = ['UIUC','PSU','BYU']
df_campus_wide.rename(columns={'state': 'Campus'})

df_ratings_by_campus = pd.melt(
    df_campus_wide,
    id_vars='state',
    value_vars=[
        'reviews_per_score_1',
        'reviews_per_score_2',
        'reviews_per_score_3',
        'reviews_per_score_4',
        'reviews_per_score_5'
    ],
    var_name='review_rating',
    value_name='num_reviews'
)

df_ratings_by_campus['review_rating'] = df_ratings_by_campus['review_rating'].str.replace('reviews_per_score_', '')
df_ratings_by_campus['percentage'] = df_ratings_by_campus.groupby('state')['num_reviews'].transform(lambda x: x / x.sum())

df_ratings_by_campus.sort_values(['state', 'review_rating'], inplace=True)

fig = px.bar(
    df_ratings_by_campus,
    x='state',
    y='percentage',
    color='review_rating',
    color_discrete_map={
        "1": "#EF5350",
        "2": "#EF9A9A",
        "3": "#FDD835",
        "4": "#9CCC65",
        "5": "#689F38"
    },
    labels={
        'review_rating': 'Review Rating',
        'state': 'Campus',
        'percentage': 'Percentage'
    },
    title='<b>Review rating breakdown by campus</b><br><span style="color: #aaa">UIUC has the highest proportion of 5 star reviews</span>',
    text=df_ratings_by_campus.apply(lambda r: f"{'⭐' * int(r['review_rating'])} {'{0:.1f}%'.format(r['percentage'] * 100)}", axis=1),
    template='simple_white',
    height=650
)

fig.update_layout(
    yaxis_tickformat=',.0%',
    uniformtext_minsize=10,
    uniformtext_mode='hide',
    font_family='Helvetica, Inter, Arial, sans-serif',
)
fig.for_each_trace(lambda t: t.update(textfont_color='white'))

fig.show()

"""#Question 2 - Which keywords (tokens) are associated with positive and negative sentiments? Are there any differences among the three campuses?"""

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

df_interesting_token_sentiment_counts = pd.DataFrame(
    { "token": [ "bug", "bug", "construction", "construction", "deposit", "deposit",
    "elevator", "elevator", "expensive", "expensive", "gym", "gym", "internet",
    "internet", "laundry", "laundry", "leak", "leak", "maintenance", "maintenance",
    "noise", "noise", "package", "package", "parking", "parking", "pet", "pet",
    "pool", "pool", "washer", "washer", ],
    "sentiment": [ "Negative", "Positive", "Negative", "Positive", "Negative",
    "Positive", "Negative", "Positive", "Negative", "Positive", "Negative",
    "Positive", "Negative", "Positive", "Negative", "Positive", "Negative",
    "Positive", "Negative", "Positive", "Negative", "Positive", "Negative",
    "Positive", "Negative", "Positive", "Negative", "Positive", "Negative",
    "Positive", "Negative", "Positive", ],
    "count": [ 158, 27, 170, 28, 1069, 132, 340, 55, 246, 145, 231, 528, 572,
    154, 323, 193, 363, 39, 1901, 2071, 205, 76, 261, 135, 1607, 799, 101, 133,
    469, 644, 225, 140, ], "percentage": [ 0.8540540540540541, 0.14594594594594595,
    0.8585858585858586, 0.1414141414141414, 0.8900915903413822, 0.10990840965861781,
    0.8607594936708861, 0.13924050632911392, 0.629156010230179, 0.37084398976982097,
    0.30434782608695654, 0.6956521739130435, 0.7878787878787878, 0.21212121212121213,
    0.625968992248062, 0.374031007751938, 0.9029850746268657, 0.09701492537313433,
    0.4786002014098691, 0.521399798590131, 0.7295373665480427, 0.2704626334519573,
    0.6590909090909091, 0.3409090909090909, 0.6679135494596842, 0.3320864505403159,
    0.43162393162393164, 0.5683760683760684, 0.42138364779874216, 0.5786163522012578,
    0.6164383561643836, 0.3835616438356164,]
})

df_interesting_token_sentiment_counts

df_interesting_token_sentiment_counts.sort_values(
    ['sentiment','percentage'],
    ascending=[True,True],
    inplace=True
)
fig=px.bar(
    df_interesting_token_sentiment_counts,
    x='percentage',
    y='token',
    template='simple_white',
    color='sentiment',
    color_discrete_map={
        'Positive': '#8bc34a',
        'Negative': '#ef5350'
    },
    labels={'token': 'Keyword','sentiment': 'Sentiment', 'percentage':'Percentage'},
    text=df_interesting_token_sentiment_counts.apply(
        lambda r: f"{'👍' if r['sentiment'] == 'Positive' else '👎'} \
        {'{0:.1f}%'.format(r['percentage'] * 100)}",
        axis=1

    )

)

fig.update_layout(
    xaxis_tickformat=',.0%',
    showlegend=False,
    title = "Keyword vs Review Sentiment Associations"
)

fig.for_each_trace(lambda t: t.update(textfont_color='white'))

fig.show()

import plotly.express as px
df_campus_positive_keywords = pd.DataFrame({'campus': ['BYU', 'BYU', 'BYU', 'PSU', 'PSU', 'PSU', 'UIUC', 'UIUC', 'UIUC'],
'token': ['Gym', 'Pet', 'Pool', 'Gym', 'Pet', 'Pool', 'Gym', 'Pet', 'Pool'],
'unique_frequency': [191, 35, 526, 259, 83, 263, 251, 57, 191],
'num_reviews': [5085, 5085, 5085, 4481, 4481, 4481, 5315, 5315, 5315],
'percentage': [0.0375614552605703,
 0.00688298918387414,
 0.10344149459193706,
 0.05779959830395001,
 0.018522651193929925,
 0.0586922561928141,
 0.04722483537158984,
 0.01072436500470367,
 0.03593603010348072]})

df_campus_positive_keywords

fig = px.bar(
   df_campus_positive_keywords,
   x = 'token',
   y = 'percentage',
   color = 'campus',
   title = "Percentage of Reviews that includes specific positive keywords",
   color_discrete_map = {
       'BYU':'dodgerblue',
       'PSU': 'navy',
       'UIUC': 'darkorange'
   },
   template = 'simple_white',
   barmode = 'group',
   labels = {
       'percentage': 'Percentage',
       'token': ' Keyword',
       'campus':'Campus'
   }
)
fig.update_layout(
   yaxis_tickformat = ', .0%'

)
fig.show()

sentiments = pd.merge(df_tokens, df_sentiments, on='review_id')
display(sentiments)

"""#Question 3 - How are the owners' response times correlated to the sentiments?"""

df_b = pd.concat([df_byu_b,df_psu_b,df_uiuc_b])
df_r = pd.concat([df_byu_r,df_psu_r,df_uiuc_r])

df_m = pd.merge(
   left = df_b,
   right = df_r,
   on = 'place_id',
   how = 'inner'
)

df_m['owner_answer_timestamp_datetime_utc'] = pd.to_datetime(df_m['owner_answer_timestamp_datetime_utc'])
df_m['review_datetime_utc'] = pd.to_datetime(df_m['review_datetime_utc'])

td = df_m['owner_answer_timestamp_datetime_utc'] - df_m['review_datetime_utc']
response_time_in_days = td.apply(lambda x:x/pd.Timedelta(days = 1))

df_m['response_time_in_days'] = np.where(
   response_time_in_days > 0,
   round(response_time_in_days,0),
   response_time_in_days
)



df_m['response_time'] = np.select(
   [
       df_m['response_time_in_days'].between (-10000, 0, inclusive = 'left'),
       df_m['response_time_in_days'].between (0, 1, inclusive = 'left'),
       df_m['response_time_in_days'].between (1, 7, inclusive = 'left'),
       df_m['response_time_in_days'].between (7, 30, inclusive = 'left'),
       df_m['response_time_in_days'].between (31, 10000, inclusive = 'left'),
   ],
   [
       'Unknown (review updated)',
       'Within a day',
       'Within a week',
       'Within a month',
       'Longer than a month',
   ],
   default = "No Response"
)

df_response_time_counts = df_m['response_time'].value_counts().to_frame().reset_index()

display(df_m)

import plotly.graph_objects as go
import plotly.express as px


fig = px.pie(
   df_response_time_counts,
   names = 'response_time',
   title = "Owner Response Times",
   values = 'count',
   template = 'simple_white',


)

fig.show()



"""#Question 4 - Is there a relationship between the review length and distribution of ratings?"""

nan_mask = df_r['review_text'].isna()
df_r['review_text'].fillna('', inplace=True)
review_text_length = df_r['review_text'].apply(len)
display(review_text_length)

df_r['review_text_length'] = df_r['review_text'].apply(len)
display(df_r)

import plotly.express as px

# Create the box plot
fig = px.box(df_r, x='review_text_length', y='review_rating', title='Review Length by Review Rating')

# Show the plot
fig.show()

"""#5 - If you were to start a managment company at UIUC what aspects seem most important to you?"""

df_uiuc = pd.merge(df_uiuc_b, df_uiuc_r, on='place_id', how='inner')
display(df_uiuc)

import pandas as pd
import plotly.graph_objects as go

# Assuming df_uiuc_b is your DataFrame with columns: 'name', 'latitude', 'longitude', 'rating'

apartments_info = {
    'location': df_uiuc_b['name'],
    'latitude': df_uiuc_b['latitude'],
    'longitude': df_uiuc_b['longitude'],
    'rating': df_uiuc_b['rating']
}
df = pd.DataFrame(apartments_info)

fig = go.Figure(go.Scattermapbox(
    lat=df['latitude'],
    lon=df['longitude'],
    mode='markers',
    marker=go.scattermapbox.Marker(
        size=df['rating'] * 10,
        color=df['rating'],
        colorscale='Greens',
        colorbar=dict(title='Rating'),
    ),
    text=df['location'] + '<br>Rating: ' + df['rating'].astype(str),
))

# Calculate the center of the map based on the average latitude and longitude
mapbox_center = {"lat": df['latitude'].mean(), "lon": df['longitude'].mean()}

fig.update_layout(
    mapbox_style="carto-positron",
    mapbox_center=mapbox_center,
    mapbox_zoom=10,
    title='Management companies location in UIUC compared to their ratings'
)

fig.show()